SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS salesDetail;
DROP TABLE IF EXISTS sale;
DROP TABLE IF EXISTS productsIncrease;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS productsForLocation;
DROP TABLE IF EXISTS patient;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS location;

SET FOREIGN_KEY_CHECKS = 1;

DROP EVENT IF EXISTS update_patient_age_daily;
SHOW EVENTS;